#!/usr/bin/env bash
# Install nginx on the server listening on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=K5O3UgLG2Jw  permanent; }' /etc/nginx/sites-available/default
service nginx restart
