#!/usr/bin/env bash
# Install nginx on the server listening on port 80
redirection="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i "48i $redirection" /etc/nginx/sites-available/default
service nginx restart
