#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop but the 9th iteration add Hi with new line
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
