#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop
# 4th iteration "bad luck"
# 8th iteration "good luck"
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
